pipeline:
  # check_formatting:
  #   image: gradle:jdk17-alpine
  #   commands:
  #     - ./gradlew lintKotlin

  # prettier_markdown_check:
  #   image: tmknom/prettier
  #   commands:
  #     - prettier -c *.md

  build_project:
    image: cimg/android:2023.05
    commands:
      - chown -R .gradle
      - ./gradlew androidDependencies
      - ./gradlew assembleDebug
