pipeline:
  # check_formatting:
  #   image: gradle:jdk17-alpine
  #   commands:
  #     - ./gradlew lintKotlin

  # prettier_markdown_check:
  #   image: tmknom/prettier
  #   commands:
  #     - prettier -c *.md

  build_project:
    image: gradle:jdk17-alpine
    commands:
      - ./gradlew assembleDebug
