pipeline:
  # check_formatting:
  #   image: cimg/android:2023.05
  #   commands:
  #     - sudo ./gradlew lintKotlin

  # prettier_markdown_check:
  #   image: tmknom/prettier
  #   commands:
  #     - prettier -c *.md

  build_project:
    image: cimg/android:2023.05
    commands:
      # - echo $ANDROID_HOME
      # - sudo chown -R $:root
      - ./gradlew assembleDebug
