pipeline:
  # check_formatting:
  #   image: cimg/android:2023.05
  #   commands:
  #     - sudo ./gradlew lintKotlin

  # prettier_markdown_check:
  #   image: tmknom/prettier
  #   commands:
  #     - prettier -c *.md

  build_project:
    image: cimg/android:2023.05
    commands:
      - id -u
      - id -g
      # - echo $ANDROID_HOME
      - sudo chown -R 1001:1002 .
      - ls -alhtr
      - ./gradlew assembleDebug
